name: Doxygen

on:
  push:
    branches:
      - main

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: html/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: html/
